### ISSUE TITLE
React Native Performance Compendium - feedback

### ISSUE THREAD

**Issue by kelset** [kelset/kelset#1]
Hello there!

If you are reading this, it 99.999% means that you saw my [Notion board about React Native performance](https://www.notion.so/The-React-Native-Performance-Compendium-21d58f64292e4074afb73a10f760f303) - and you have something to say about it!

Please post it below 👇

**Comment by mrousavy** [comment]
thanks for the compendium, i love it! 🎉

**Comment by kelset** [comment]
closing this one off, I've retired the board
