### ISSUE TITLE
The React Native Community Map - feedback

### ISSUE THREAD

**Issue by kelset** [kelset/kelset#3]
Hello there!

If you are reading this, it 99.999% means that you saw my [Notion board about the React Native Community](https://lifeiswhat.notion.site/The-React-Native-Community-Map-07f3221c294d4c8ab65a13cf1dee6901) - and you have something to say about it!

Please post it below 👇

**Comment by vcarl** [comment]
We don't have a dedicated feed for it (yet?) but we discuss React Native on our This Month in React events in Reactiflux! Me, Mark Erikson, and Sebastien Lorber 🙂 https://podcasters.spotify.com/pod/show/reactiflux/

**Comment by yjose** [comment]
I would love to add [the starter we are working on](https://github.com/obytes/react-native-template-obytes) to the list of apps. I believe many people could benefit from it.

**Comment by kelset** [comment]
> We don't have a dedicated feed for it (yet?) but we discuss React Native on our This Month in React events in Reactiflux! Me, Mark Erikson, and Sebastien Lorber 🙂 [podcasters.spotify.com/pod/show/reactiflux](https://podcasters.spotify.com/pod/show/reactiflux/)

Good stuff, thanks @vcarl! Since I already listed the This Week in React newsletter and the Reactiflux discord, this one fits well :)

**Comment by kelset** [comment]
> I would love to add [the starter we are working on](https://github.com/obytes/react-native-template-obytes) to the list of apps. I believe many people could benefit from it.

Sorry but at least for now that list will only have actual apps out in production that are fully open source

**Comment by lokesh020** [comment]
Thanks @kelset for amazing stuff and helping community.
I would like to add a youtube channel link which may be useful for community
https://www.youtube.com/@Codevolution/videos

**Comment by kelset** [comment]
> Thanks @kelset for amazing stuff and helping community. I would like to add a youtube channel link which may be useful for community [youtube.com/@Codevolution/videos](https://www.youtube.com/@Codevolution/videos)

added, thanks!

**Comment by sekhsoukh123** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

byaruhaf, @evianzhow, @haotianling, @arturparkhisenko, @bitcrumb, @chetan, @kristiyandobrev, @junchen108, @gxdmachine, @Joannis, @michaelhenry, @sattiti, @ischlecken, @r-peck, @vishalgabani, @pangpingfei, @JohnnyTseng, @ethnt, @Cordobo, @smileykevin

**Comment by kelset** [comment]
closing this one off, I've retired the board. Please refer to https://github.com/kelset/react-native-community-map instead
